AWATempleteFormatVersion: "2010-09-09"

Description: Create small VPC for FridayHITT company

Resources:

  myNestedVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        -Key: Name
        Value: MyNestedVPC

  IGW:
    Types: AWS::EC2::InternetGateway
    Properties:
      Tags:
        -Key: Name
        Value: IGW

# attach IGW to VPC
  IGWAttachment:
    Type: AWS::EC"::VPCAttachment
    Properties:
      InternetGatwayId: !Ref IGW
      VpcId: !Ref VPC




  