AWSTemplateFormatVersion: "2010-09-09"

Resources:
  DBSubnetGruop:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "subnet group"
        SubnetIds:
          - Fn::ImportValue: HITTvpc-PrivateDBSubnet1
          - Fn::ImportValue: HITTvpc-PrivateDBSubnet2
        Tags:
          - Key: Name
            Value: DBSubnetGroup

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      AvailabilityZone:  eu-west-1a
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: mysqldb
      DBName: '{{resolve:ssm:dbName:1}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: MySQL
      #ENgineVersion: 8.0.28
      MasterUserName: '{{resolve:ssm:dbUserName:1}}'
      MasterUserPassword: '{{resolve:ssm:dbUserPassword:1}}'
      MultiAZ: false 
      VPCSecurityGroups:
        - Fn::ImportValue : HITTvpc-DBSecurityGroup
       #Fn::ImportValue
       #'Fn::Sub': '${AWS::StackName}-DBSecurityGroupID'
